image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip3 install -r requirements.txt
    command: clear && python3 main.py
    name: Split terminal
  - openMode: split-right
    command: echo SplitTerminal && clear