a = input('Digite algo: ')
print('O tipo primitivo desse valor é: ',type(a))
print('So tem espaços? ',a.isspace())
print('e um numero? ',a.isnumeric())
print('E alfabetico? ',a.isalpha())
print('E alfanumerico? ',a.isalnum())
print('Esta em maisculas? ',a.isupper())
print('Esta em minuscula? ',a.islower())
print('Esta capitalizada? ',a.istitle())
